name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - msrv # Minimum Supported Rust Version, see below
        features:
          - default
          - ''

    steps:
      - uses: actions/checkout@v2

      - uses: haya14busa/action-cond@v1
        id: toolchain
        with:
          cond: ${{ matrix.rust == 'msrv' }}
          if_true: 1.44.1
          if_false: ${{ matrix.rust }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ steps.toolchain.outputs.value }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features '${{ matrix.features }}'

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
